apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana_data
        - name: grafana-datasources
          hostPath:
            path: /grafana/datasources
            type: Directory
        - name: grafana-dashboards
          hostPath: 
            path: /grafana/dashboards
            type: Directory
            #TODO: hostPaths are wrong, should be absolute path. May need PV and PVC
        - name: grafana-setup
          hostPath:
            path: /grafana/setup.sh
            type: Directory
      containers:
        - name: grafana
          image: grafana/grafana:latest-ubuntu
          limits:
            cpu:
            memory: #TODO: add limits
          command: ["/setup.sh"]
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: GF_INSTALL_PLUGINS
              value: "grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel"
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
          ports:
            - containerPort: 3000
          restartPolicy: Always
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/datasources
            - name: grafana-dashboards
              mountPath: /etc/grafana/dashboards
            - name: grafana-setup
              mountPath: /setup.sh

